Make several lyon crates no_std
nical/lyon pull request #831
Opened 2022-10-19 22:12 UTC by notgull

This PR makes several crates `no_std`. These crates did not depend on `libstd` for anything save for floating point functions, which are now used through the `num_traits` crate. The `num_traits` crate has its `libm` feature enabled. When the `std` feature is enabled on the affected crates, the `std` feature is in turn enabled on `num_traits`, avoiding the use of `libm` on targets with built-in floating point operations.

The crates I've converted are:

- `lyon_geom`
- `lyon_path` (still uses `alloc`)
- `lyon_algorithms` (still uses `alloc`)

2022-10-26 07:43 UTC, nical commented
Hi, thanks for this PR. Do you have motivating use case for using lyon crates in a no-std context?

2022-10-26 13:43 UTC, notgull commented
I am currently writing a GUI framework that I'd like to be `no_std`, e.g. it's welded directly to libxcb and doesn't need libstd at all (largely for code bloat reasons). I'd like to use these crates to provide geometric primitives for this framework. In order to fit, these crates would need to be no_std.

2022-11-05 11:53 UTC, nical requested changes
Sorry for the delay, I've been away from computers for a bit. Thanks for explaining the motivation, sounds good to me.

Just one thing: If I understand correctly, with this change libm will be used by default, I'd rather have libm only used in the no-std mode as libm is reportedly slower for at least some of the provided math utilities.

2022-11-05 13:17 UTC, notgull commented
The `num-traits` crate only uses `libm` if `libstd` primitives are not available. Therefore, when the `std` feature is enabled, this should not be an issue.

2022-11-05 21:02 UTC, nical commented
You are right, my bad. Good to know.

2022-11-05 21:02 UTC, merged